---
- name: Mise à jour des paquets et installation de python3-pip
  apt:
    name: python3-pip
    state: present
    update_cache: true

- name: Installer le module PyMySQL pour Python 3
  pip:
    name: PyMySQL
    state: present
  when: ansible_python_version.startswith('3')

- name: Configurer le mot de passe root MySQL
  debconf:
    name: mysql-server
    question: "mysql-server/root_password"
    value: "{{ mysql_root_password }}"
    vtype: "password"

- name: Confirmer le mot de passe root MySQL
  debconf:
    name: mysql-server
    question: "mysql-server/root_password_again"
    value: "{{ mysql_root_password }}"
    vtype: "password"

- name: Installer MySQL Server
  apt:
    name: mysql-server
    state: present
    update_cache: true

- name: Démarrer et activer MySQL
  service:
    name: mysql
    state: started
    enabled: true

- name: Modifier l'écoute MySQL pour accepter les connexions externes
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: "bind-address = {{ mysql_bind_address }}"
    backup: yes

- name: Redémarrer mysql
  service:
    name: mysql
    state: restarted

- name: Créer une base de données pour CodeIgniter
  mysql_db:
    name: "{{ codeigniter_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "localhost"
    login_unix_socket: "{{ mysql_socket_path | default('/var/run/mysqld/mysqld.sock') }}"  # Socket par défaut

- name: Créer un utilisateur MySQL pour CodeIgniter
  mysql_user:
    name: "{{ codeigniter_user }}"
    host: '%'
    password: "{{ codeigniter_password }}"
    priv: "{{ mysql_privileges }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "%"
    login_unix_socket: "{{ mysql_socket_path | default('/var/run/mysqld/mysqld.sock') }}"  # Socket par défaut

