version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"

  express1:
    build:
      context: ./express1
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  express2:
    build:
      context: ./express2
      dockerfile: Dockerfile
    ports:
      - "3002:3002"

  express3:
    build:
      context: ./express3
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
