network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
    eth1:
      addresses:
        - 192.168.10.97/28   # IP Addresss net3
      nameservers:
        addresses:
          - 192.168.10.3
          - 192.168.10.99
        search: 
          - ssi.edu  
    eth2:
      addresses:
        - 192.168.10.114/30 # IP Address netR2-R3
      routes:
        - to: 192.168.10.0/26     # Route to net1
          via: 192.168.10.113      
    eth3:
      addresses:
        - 192.168.10.122/30 # IP Address netR1-R2
      routes:
        - to: 192.168.10.64/27     # Route to net2
          via: 192.168.10.121
