network:
  version: 2
  ethernets:
    eth1:
      addresses:
        - 192.168.10.98/28  
      gateway4: 192.168.10.97  
      nameservers:
        addresses:
          - 192.168.10.3
          - 192.168.10.99
        search: 
          - ssi.edu
