network:
  version: 2
  ethernets:
    eth1:
      addresses:
        - 192.168.10.67/27  # Adresse IP pour DHCP sur net2
      gateway4: 192.168.10.65  # Passerelle (gateway) pour net2
      nameservers:
        addresses:
          - 192.168.10.3
          - 192.168.10.99
        search: 
          - ssi.edu