network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.1.110/28   
    eth1:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.1.114/30    
      routes:
        - to: 192.168.1.64/27 
          via: 192.168.1.113 
    eth2:
      addresses:
        - 192.168.1.121/30
      routes:
        - to: 192.168.1.0/26
          via: 192.168.1.122