network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.1.94/27  
    eth1:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.1.113/30    
      routes:
        - to: 192.168.1.96/28 
          via: 192.168.1.114

    eth2:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.1.117/30    
      routes:
        - to: 192.168.1.0/26 
          via: 192.168.1.118 
