---
- name: Install and Configure Proxmox VE
  hosts: proxmox3    # Le groupe ou hôte sur lequel exécuter les tâches
  become: true       # Exécute les tâches avec des privilèges root
  gather_facts: yes 
  tasks:    
    - name: Add Proxmox GPG key 
      ansible.builtin.get_url:
        url: "https://enterprise.proxmox.com/debian/proxmox-release-{{ ansible_distribution_release }}.gpg"
        dest: "/etc/apt/trusted.gpg.d/proxmox-release-{{ ansible_distribution_release }}.gpg"
        owner: root
        group: root
        mode: "0644"

    - name: Add Proxmox repository and update cache
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
        state: present
        update_cache: true

    - name: Remove enterprise repo
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

