---
- name: Configure NFS Server and Add Storage to Proxmox
  hosts: nfs
  become: false
  vars:
    export_net1: "192.168.38.0/24"
    export_net2: "192.168.3.0/24"
  tasks:
    # 1. Installer le serveur NFS
    - name: Install NFS server
      apt:
        name: nfs-kernel-server
        state: present

    # 2. Créer le répertoire à partager
    - name: Create NFS share directory
      file:
        path: /srv/proxmox-nfs
        state: directory
        mode: '0777'

    # 3. Configurer le partage NFS
    - name: Configure NFS exports
      lineinfile:
        path: /etc/exports
        line: "/srv/proxmox-nfs {{ export_net1 }}(rw,sync,no_root_squash,no_subtree_check) {{ export_net2 }}(rw,sync,no_root_squash,no_subtree_check)"
        create: yes

    # 4. Redémarrer le service NFS
    - name: Restart NFS server
      systemd:
        name: nfs-kernel-server
        state: restarted

    # 5. Activer NFS au démarrage
    - name: Enable NFS server on boot
      systemd:
        name: nfs-kernel-server
        enabled: true

