network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
    eth1:
      addresses:
        - 192.168.10.1/26   # Adresse IP sur net1
      nameservers:
        addresses:
          - 192.168.10.3
          - 192.168.10.99
        search: 
          - ssi.edu        
    eth2:
      addresses:
        - 192.168.10.117/30 # Adresse IP sur netR1-R3
      routes:
        - to: 192.168.10.64/27     # Route vers le réseau 2
          via: 192.168.10.118
    eth3:
      addresses:
        - 192.168.10.113/30 # Adresse IP sur netR2-R3
      routes:
        - to: 192.168.10.96/28     # Route vers netR2-R3
          via: 192.168.10.114

