network:
  version: 2
  ethernets:
    eth1:
      addresses:
        - 192.168.10.3/26  # Adresse IP pour DNSMaster sur net1
      gateway4: 192.168.10.1  # Passerelle (gateway) pour net1
      nameservers:
        addresses:
          - 192.168.10.3
          - 192.168.10.99
        search: 
          - ssi.edu
