network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.1.62/26
    eth1:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.1.118/30
      routes:
        - to: 192.168.1.64/27
          via: 192.168.1.117
    eth2:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.1.122/30
      routes:
        - to: 192.168.1.96/28
          via: 192.168.1.121
