---
- name: Deploy CodeIgniter4 webapp
  hosts: webservers
  become: true
  roles:
    - apache
    - codeigniter

- name: Config MySQL database
  hosts: dbservers
  become: true
  roles:
    - mysql
