network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
    eth1:
      addresses:
        - 192.168.10.65/27   # IP address net2
      nameservers:
        addresses:
          - 192.168.10.3
          - 192.168.10.99
        search: 
          - ssi.edu        
    eth2:
      addresses:
        - 192.168.10.118/30 # IP address netR1-R3
      routes:
        - to: 192.168.10.0/26     # Route to net1
          via: 192.168.10.117      
    eth3:
      addresses:
        - 192.168.10.121/30 # Ip Address netR1-R2
      routes:
        - to: 192.168.10.96/28     # Route to net3
          via: 192.168.10.122     
