---
    - name: install nginx
      apk:
        name: nginx
        state: present
        update_cache: yes

    - name: Check "{{ nginx_user }}" user exists
      user:
        name: "{{ nginx_user }}"
        group: "{{ nginx_group }}"
        state: present

    - name: deploy custom nginx conf
      template:
        src: nginx.conf.j2
        dest: "/etc/nginx/http.d/{{ SNAME }}.conf"
      notify: 
        #- restart nginx

    - name: validate nginx conf
      command: nginx -t
      register: nginx_test
      failed_when: nginx_test.rc != 0
      notify:
        - restart nginx

    - name: check nginx service is running
      service:
        name: nginx
        state: started
        enabled: yes

